name: Build

on:
  push:
    tags:
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'      
      - name: Go Version
        run: |
          go version

      - name: Test & Build
        if: always()
        run: |
            go get ./...
            go vet ./...
            go install gotest.tools/gotestsum@latest
            gotestsum --format testname -- -v -p 10 -count 1 -coverprofile cover.out ./...

      - name: Release
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}